### ISSUE TITLE
Crash with Java 11

### ISSUE THREAD

**Issue by Keyraus** [masterX244/SenaFirmwareUtils#1]
When launching .bat file, I get this error : 
Error : Cannot find or load main class : de.nplusc.izc.senabitwiggler.EntryPoint
Caused by : java.lang.ClassNotFoundException: de.nplusc.izc.senabitwiggler.EntryPoint

When launching directly .jar file, I get the same error : 

Exception in thread "main" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/Yaml
        at de.nplusc.izc.senabitwiggler.EntryPoint.main(EntryPoint.java:41)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.Yaml
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 1 more

Running Java 11 on Windows 10 Pro 21H2 x64

![image](https://user-images.githubusercontent.com/46033182/161267554-5f950139-1b07-487a-abef-760875cf7449.png)

**Comment by masterX244** [comment]
Jar file should not be launched directly. Gradle bat file sets the classpath.
The error message of the bat file is the important one. 

Also: pushed my latest code which uses Java17 now. Recheck with that please. 
If it still crashes post the entire error message thrown by the batch file
